### ISSUE TITLE
Input Control of operation needs type checking when value is pushed

### ISSUE THREAD

**Issue by robigan** [wierkstudio/ciphereditor#10]

**Comment by robigan** [comment]
Ignore the accidental Enter key press

**Comment by robigan** [comment]
This is what I wrote on the Discord, this bug is here for documentation purposes.

Also the input control of an operation needs to do it's own type checking when being fed values from a control that can change it's type and convert if appropriate/possible
![image](https://user-images.githubusercontent.com/35210888/188448312-917786dd-3647-4a01-a83e-1308dcc4e18d.png)

**Comment by ffraenz** [comment]
This is a known issue. Validation for control values has not been implemented, yet. I'll close this issue and open a new one documenting what I plan on doing here.
