### ISSUE TITLE
Make overflow of add-modal auto/scrollable

### ISSUE THREAD

**Issue by robigan** [wierkstudio/ciphereditor#11]
What the title says, issue is for documentation purposes. I'll probably fix it with my latest PR

**Comment by ffraenz** [comment]
I'm not sure if I understand you correctly. As of now, the modals are scrollable when they exceed the height of the viewport. The strategy currently implemented also makes sure (large) modals are accessible on mobile both in standalone and when the app is embedded within the website. I decided against making the content of a modal scrollable as it often leads to a worse user experience (e.g. bad experience on touch devices, users not recognizing that content is scrollable). I don't intend to make changes here if there's no important reason for it (e.g. accessibility or buggy behavior). I'll close this issue. Please reopen it if you still think you found a bug or if you want to make your case for changing the way modals are scrolled right now.
