### ISSUE TITLE
Feature: Delete object button

### ISSUE THREAD

**Issue by TJCgames** [wierkstudio/ciphereditor#16]
### Describe your feature or enhancement suggestion

A button to delete objects, such as operations and pathways
To be honest, I'm not sure why it isn't in the program.

**Comment by TJCgames** [comment]
nvm im blind

**Comment by ffraenz** [comment]
I'm actually working on an update where the delete button makes an appearance in the top toolbar :) In the meantime you can also press the delete or backspace key to remove a node.
