### ISSUE TITLE
Bug: Breaks on chromeOS

### ISSUE THREAD

**Issue by TJCgames** [wierkstudio/ciphereditor#17]
### Describe the current behavior
When I try to place an operation, like the viginere cipher operation, the ui disappears and I cannot use the website

### Describe the expected behavior
The operation gets placed and the ui remains on the screen

### Steps to reproduce the bug

1. Get a chromebook or similar
2. Navigate to [ciphereditor.com](https://ciphereditor.com).
3. Try to place an operation «EDIT: also happens when exiting a program operation»

### Version, Environment, Platform

- ciphereditor version: I cannot find where it says the version
- Browser and browser version (if applicable): Google Chrome 107.0.5304.110 x64
- Operating system: chromeOS

**Comment by ffraenz** [comment]
Oh, that's interesting! Are you able to post the content of the dev tools console (stack trace or screenshot of it)? I have no Chrome OS at hand, right now.

**Comment by TJCgames** [comment]
when adding a viginere cipher operation:

index.bc3e647f.js:57 Error: Minified React error #185; visit https://reactjs.org/docs/error-decoder.html?invariant=185 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at Ct (index.bc3e647f.js:57:33996)
    at wv (index.bc3e647f.js:55:22379)
    at Object.callback (index.bc3e647f.js:55:22242)
    at index.bc3e647f.js:72:2081
    at Id (index.bc3e647f.js:57:37135)
    at Object.notify (index.bc3e647f.js:72:2056)
    at Object.i [as notifyNestedSubs] (index.bc3e647f.js:72:2469)
    at a (index.bc3e647f.js:72:2510)
    at h (index.bc3e647f.js:2:86481)
    at index.bc3e647f.js:72:67366
Xu @ index.bc3e647f.js:57
Pv.n.callback @ index.bc3e647f.js:57
tp @ index.bc3e647f.js:55
gp @ index.bc3e647f.js:57
Yv @ index.bc3e647f.js:57
Zb @ index.bc3e647f.js:57
Gb @ index.bc3e647f.js:57
Bn @ index.bc3e647f.js:57
xp @ index.bc3e647f.js:57
Vn @ index.bc3e647f.js:55
(anonymous) @ index.bc3e647f.js:57
index.bc3e647f.js:57 Uncaught Error: Minified React error #185; visit https://reactjs.org/docs/error-decoder.html?invariant=185 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at Ct (index.bc3e647f.js:57:33996)
    at wv (index.bc3e647f.js:55:22379)
    at Object.callback (index.bc3e647f.js:55:22242)
    at index.bc3e647f.js:72:2081
    at Id (index.bc3e647f.js:57:37135)
    at Object.notify (index.bc3e647f.js:72:2056)
    at Object.i [as notifyNestedSubs] (index.bc3e647f.js:72:2469)
    at a (index.bc3e647f.js:72:2510)
    at h (index.bc3e647f.js:2:86481)
    at index.bc3e647f.js:72:67366

**Comment by TJCgames** [comment]
before i placed the operation:

content-script.js:1 Sending message to background page sw-shouldActivate
content-script.js:1 Hiding page content
content-script.js:1 Successfully hid page content
content-script.js:1 Received message from background page: "sw-rescan"
content-script.js:1 Ignoring first request for re-scan
content-script.js:1 Received message from background page: "sw-rescan"
content-script.js:1 Re-scanning page content
content-script.js:1 Running scrape dom 1
content-script.js:1 Sending message to background page {pageContent: '<html lang="en-us" class="root root--script-enable…ormal;"></p></next-route-announcer></body></html>', pageLocation: 'https://ciphereditor.com/?utm_campaign=cryptii&amp;utm_source=referrer&amp;utm_medium=textlink', pageTitle: 'Your playground for cryptography, coding & data - ciphereditor', rescan: false}
content-script.js:1 Sending message to background page sw-shouldActivate
content-script.js:1 Running scrape dom 1
content-script.js:1 Sending message to background page {pageContent: '<html lang="en-us" class="root root--script-enable…n0%3d" style="position: absolute;"></body></html>', pageLocation: 'https://ciphereditor.com/?utm_campaign=cryptii&amp;utm_source=referrer&amp;utm_medium=textlink', pageTitle: 'Your playground for cryptography, coding & data - ciphereditor', rescan: Array(1)}
content-script.js:1 Received message from background page: {
 "actionCode": [
  3
 ],
 "contentModsToApply": [
  "477"
 ],
 "debug": false,
 "metadataVersion": 3
}
content-script.js:1 Received message to modify dom
content-script.js:1 Displaying page again
content-script.js:1 Received message from background page: {
 "actionCode": [
  3
 ],
 "contentModsToApply": [
  "477"
 ],
 "debug": false,
 "metadataVersion": 3
}
content-script.js:1 Received message to modify dom
content-script.js:1 Displaying page again
content-script.js:1 Received message from background page: {
 "actionCode": [
  3
 ],
 "contentModsToApply": [
  "477"
 ],
 "debug": false,
 "metadataVersion": 3
}
content-script.js:1 Received message to modify dom
content-script.js:1 Displaying page again
content-script.js:1 Received message from background page: {
 "actionCode": [
  3
 ],
 "contentModsToApply": [
  "477"
 ],
 "debug": false,
 "metadataVersion": 3
}
content-script.js:1 Received message to modify dom
content-script.js:1 Displaying page again
content-script.js:1 Hiding page content
content-script.js:1 Successfully hid page content
content-script.js:1 Running scrape dom 1
content-script.js:1 Sending message to background page {pageContent: '<html lang="en" class="root root--script-disabled …block; left: 0px; top: 0px;"></div></body></html>', pageLocation: 'https://app.ciphereditor.com/', pageTitle: 'ciphereditor', rescan: false}
content-script.js:1 Received message from background page: {
 "actionCode": [
  3
 ],
 "contentModsToApply": [
  "477"
 ],
 "debug": false,
 "metadataVersion": 3
}
content-script.js:1 Received message to modify dom
content-script.js:1 Displaying page again
content-script.js:1 Received message from background page: {
 "actionCode": [
  3
 ],
 "contentModsToApply": [
  "477"
 ],
 "debug": false,
 "metadataVersion": 3
}
content-script.js:1 Received message to modify dom
content-script.js:1 Displaying page again

**Comment by ffraenz** [comment]
I just deployed a new version where sourcemaps are present and where Sentry, an error reporting tool, is configured. Would you revisit the app? I should receive a more detailed error report that hopefully gives me a hint about where in the code the issue lies. I'll install chrome OS in the meantime.

**Comment by TJCgames** [comment]
it works

**Comment by TJCgames** [comment]
ok yea it works

**Comment by ffraenz** [comment]
Okay, well. The update is deploying as we speak, I'm not sure why it works already for you :)

I received a similar issue causing the same React error "Maximum update depth exceeded" and found out that it has something to do with how nodes sizes and positions are measured on the canvas. I refactored this code and switched to a different strategy (using ResizeObservers).

Would you hit refresh (once again) and check if it still works after the deployment? It just went through.

**Comment by TJCgames** [comment]
I am not at school atm
