### ISSUE TITLE
Bug: RC4 cipher is broken

### ISSUE THREAD

**Issue by QuackitsQuinn** [wierkstudio/ciphereditor#21]
### Describe the current behavior
Modifying any of the inputs for the RC4 causes it to error with "Failed to execute 'importScripts' on 'WorkerGlobalScope': The script at 'https://localhost:3010/extensions/essentials/extension.js' failed to load."

### Describe the expected behavior
A successful output without an error

### Steps to reproduce the bug

1. Navigate to [ciphereditor.com](https://ciphereditor.com).
2. Change any of the RC4 parameters 

### Version, Environment, Platform

- ciphereditor version: dev.ciphereditor.com & ciphereditor.com
- Browser and browser version (if applicable): Chrome 108.0.5359.71
- Operating system: macOS monterey

**Comment by ffraenz** [comment]
Hi there! Thank you for reporting this issue. I must have left behind a url that only works in my local development environment. I just deployed an update to fix it. Please let me know if this works for you.

**Comment by QuackitsQuinn** [comment]
This works now. Thank you!
